### ISSUE TITLE
help

### ISSUE THREAD

**Issue by gapemaster3** [VeryBigSad/telegram_to_vk#3]
"someone sent a message from a chat that is not the one that I monitor"

please I have tried my channel id, channel name, channe invite link, my telegram user id, my username and still the same....

**Comment by VeryBigSad** [comment]
hey! this seems like a config problem
you could contact me on telegram for assistance, since it could potentially have some sensitive data you wouldn't wanna share in a github issue
My telegram: @Mikhail_Khromov
